'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.573
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Data
Imports System.Runtime.Serialization
Imports System.Xml


<Serializable(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Diagnostics.DebuggerStepThrough(),  _
 System.ComponentModel.ToolboxItem(true)>  _
Public Class DSFrmRepBank
    Inherits DataSet
    
    Private tablebank As bankDataTable
    
    Private tablevendor As vendorDataTable
    
    Private tableaccount As accountDataTable
    
    Public Sub New()
        MyBase.New
        Me.InitClass
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    Protected Sub New(ByVal info As SerializationInfo, ByVal context As StreamingContext)
        MyBase.New
        Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(System.String)),String)
        If (Not (strSchema) Is Nothing) Then
            Dim ds As DataSet = New DataSet
            ds.ReadXmlSchema(New XmlTextReader(New System.IO.StringReader(strSchema)))
            If (Not (ds.Tables("bank")) Is Nothing) Then
                Me.Tables.Add(New bankDataTable(ds.Tables("bank")))
            End If
            If (Not (ds.Tables("vendor")) Is Nothing) Then
                Me.Tables.Add(New vendorDataTable(ds.Tables("vendor")))
            End If
            If (Not (ds.Tables("account")) Is Nothing) Then
                Me.Tables.Add(New accountDataTable(ds.Tables("account")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.InitClass
        End If
        Me.GetSerializationData(info, context)
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    <System.ComponentModel.Browsable(false),  _
     System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property bank As bankDataTable
        Get
            Return Me.tablebank
        End Get
    End Property
    
    <System.ComponentModel.Browsable(false),  _
     System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property vendor As vendorDataTable
        Get
            Return Me.tablevendor
        End Get
    End Property
    
    <System.ComponentModel.Browsable(false),  _
     System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property account As accountDataTable
        Get
            Return Me.tableaccount
        End Get
    End Property
    
    Public Overrides Function Clone() As DataSet
        Dim cln As DSFrmRepBank = CType(MyBase.Clone,DSFrmRepBank)
        cln.InitVars
        Return cln
    End Function
    
    Protected Overrides Function ShouldSerializeTables() As Boolean
        Return false
    End Function
    
    Protected Overrides Function ShouldSerializeRelations() As Boolean
        Return false
    End Function
    
    Protected Overrides Sub ReadXmlSerializable(ByVal reader As XmlReader)
        Me.Reset
        Dim ds As DataSet = New DataSet
        ds.ReadXml(reader)
        If (Not (ds.Tables("bank")) Is Nothing) Then
            Me.Tables.Add(New bankDataTable(ds.Tables("bank")))
        End If
        If (Not (ds.Tables("vendor")) Is Nothing) Then
            Me.Tables.Add(New vendorDataTable(ds.Tables("vendor")))
        End If
        If (Not (ds.Tables("account")) Is Nothing) Then
            Me.Tables.Add(New accountDataTable(ds.Tables("account")))
        End If
        Me.DataSetName = ds.DataSetName
        Me.Prefix = ds.Prefix
        Me.Namespace = ds.Namespace
        Me.Locale = ds.Locale
        Me.CaseSensitive = ds.CaseSensitive
        Me.EnforceConstraints = ds.EnforceConstraints
        Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
        Me.InitVars
    End Sub
    
    Protected Overrides Function GetSchemaSerializable() As System.Xml.Schema.XmlSchema
        Dim stream As System.IO.MemoryStream = New System.IO.MemoryStream
        Me.WriteXmlSchema(New XmlTextWriter(stream, Nothing))
        stream.Position = 0
        Return System.Xml.Schema.XmlSchema.Read(New XmlTextReader(stream), Nothing)
    End Function
    
    Friend Sub InitVars()
        Me.tablebank = CType(Me.Tables("bank"),bankDataTable)
        If (Not (Me.tablebank) Is Nothing) Then
            Me.tablebank.InitVars
        End If
        Me.tablevendor = CType(Me.Tables("vendor"),vendorDataTable)
        If (Not (Me.tablevendor) Is Nothing) Then
            Me.tablevendor.InitVars
        End If
        Me.tableaccount = CType(Me.Tables("account"),accountDataTable)
        If (Not (Me.tableaccount) Is Nothing) Then
            Me.tableaccount.InitVars
        End If
    End Sub
    
    Private Sub InitClass()
        Me.DataSetName = "DSFrmRepBank"
        Me.Prefix = ""
        Me.Namespace = "http://www.tempuri.org/DSFrmRepBank.xsd"
        Me.Locale = New System.Globalization.CultureInfo("fa-IR")
        Me.CaseSensitive = false
        Me.EnforceConstraints = true
        Me.tablebank = New bankDataTable
        Me.Tables.Add(Me.tablebank)
        Me.tablevendor = New vendorDataTable
        Me.Tables.Add(Me.tablevendor)
        Me.tableaccount = New accountDataTable
        Me.Tables.Add(Me.tableaccount)
    End Sub
    
    Private Function ShouldSerializebank() As Boolean
        Return false
    End Function
    
    Private Function ShouldSerializevendor() As Boolean
        Return false
    End Function
    
    Private Function ShouldSerializeaccount() As Boolean
        Return false
    End Function
    
    Private Sub SchemaChanged(ByVal sender As Object, ByVal e As System.ComponentModel.CollectionChangeEventArgs)
        If (e.Action = System.ComponentModel.CollectionChangeAction.Remove) Then
            Me.InitVars
        End If
    End Sub
    
    Public Delegate Sub bankRowChangeEventHandler(ByVal sender As Object, ByVal e As bankRowChangeEvent)
    
    Public Delegate Sub vendorRowChangeEventHandler(ByVal sender As Object, ByVal e As vendorRowChangeEvent)
    
    Public Delegate Sub accountRowChangeEventHandler(ByVal sender As Object, ByVal e As accountRowChangeEvent)
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class bankDataTable
        Inherits DataTable
        Implements System.Collections.IEnumerable
        
        Private columncod As DataColumn
        
        Private columnname As DataColumn
        
        Private columnflag As DataColumn
        
        Friend Sub New()
            MyBase.New("bank")
            Me.InitClass
        End Sub
        
        Friend Sub New(ByVal table As DataTable)
            MyBase.New(table.TableName)
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
            Me.DisplayExpression = table.DisplayExpression
        End Sub
        
        <System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        Friend ReadOnly Property codColumn As DataColumn
            Get
                Return Me.columncod
            End Get
        End Property
        
        Friend ReadOnly Property nameColumn As DataColumn
            Get
                Return Me.columnname
            End Get
        End Property
        
        Friend ReadOnly Property flagColumn As DataColumn
            Get
                Return Me.columnflag
            End Get
        End Property
        
        Public Default ReadOnly Property Item(ByVal index As Integer) As bankRow
            Get
                Return CType(Me.Rows(index),bankRow)
            End Get
        End Property
        
        Public Event bankRowChanged As bankRowChangeEventHandler
        
        Public Event bankRowChanging As bankRowChangeEventHandler
        
        Public Event bankRowDeleted As bankRowChangeEventHandler
        
        Public Event bankRowDeleting As bankRowChangeEventHandler
        
        Public Overloads Sub AddbankRow(ByVal row As bankRow)
            Me.Rows.Add(row)
        End Sub
        
        Public Overloads Function AddbankRow(ByVal name As String, ByVal flag As Boolean) As bankRow
            Dim rowbankRow As bankRow = CType(Me.NewRow,bankRow)
            rowbankRow.ItemArray = New Object() {Nothing, name, flag}
            Me.Rows.Add(rowbankRow)
            Return rowbankRow
        End Function
        
        Public Function FindBycod(ByVal cod As Short) As bankRow
            Return CType(Me.Rows.Find(New Object() {cod}),bankRow)
        End Function
        
        Public Function GetEnumerator() As System.Collections.IEnumerator Implements System.Collections.IEnumerable.GetEnumerator
            Return Me.Rows.GetEnumerator
        End Function
        
        Public Overrides Function Clone() As DataTable
            Dim cln As bankDataTable = CType(MyBase.Clone,bankDataTable)
            cln.InitVars
            Return cln
        End Function
        
        Protected Overrides Function CreateInstance() As DataTable
            Return New bankDataTable
        End Function
        
        Friend Sub InitVars()
            Me.columncod = Me.Columns("cod")
            Me.columnname = Me.Columns("name")
            Me.columnflag = Me.Columns("flag")
        End Sub
        
        Private Sub InitClass()
            Me.columncod = New DataColumn("cod", GetType(System.Int16), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columncod)
            Me.columnname = New DataColumn("name", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnname)
            Me.columnflag = New DataColumn("flag", GetType(System.Boolean), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnflag)
            Me.Constraints.Add(New UniqueConstraint("Constraint1", New DataColumn() {Me.columncod}, true))
            Me.columncod.AutoIncrement = true
            Me.columncod.AllowDBNull = false
            Me.columncod.ReadOnly = true
            Me.columncod.Unique = true
        End Sub
        
        Public Function NewbankRow() As bankRow
            Return CType(Me.NewRow,bankRow)
        End Function
        
        Protected Overrides Function NewRowFromBuilder(ByVal builder As DataRowBuilder) As DataRow
            Return New bankRow(builder)
        End Function
        
        Protected Overrides Function GetRowType() As System.Type
            Return GetType(bankRow)
        End Function
        
        Protected Overrides Sub OnRowChanged(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.bankRowChangedEvent) Is Nothing) Then
                RaiseEvent bankRowChanged(Me, New bankRowChangeEvent(CType(e.Row,bankRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowChanging(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.bankRowChangingEvent) Is Nothing) Then
                RaiseEvent bankRowChanging(Me, New bankRowChangeEvent(CType(e.Row,bankRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleted(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.bankRowDeletedEvent) Is Nothing) Then
                RaiseEvent bankRowDeleted(Me, New bankRowChangeEvent(CType(e.Row,bankRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleting(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.bankRowDeletingEvent) Is Nothing) Then
                RaiseEvent bankRowDeleting(Me, New bankRowChangeEvent(CType(e.Row,bankRow), e.Action))
            End If
        End Sub
        
        Public Sub RemovebankRow(ByVal row As bankRow)
            Me.Rows.Remove(row)
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class bankRow
        Inherits DataRow
        
        Private tablebank As bankDataTable
        
        Friend Sub New(ByVal rb As DataRowBuilder)
            MyBase.New(rb)
            Me.tablebank = CType(Me.Table,bankDataTable)
        End Sub
        
        Public Property cod As Short
            Get
                Return CType(Me(Me.tablebank.codColumn),Short)
            End Get
            Set
                Me(Me.tablebank.codColumn) = value
            End Set
        End Property
        
        Public Property name As String
            Get
                Try 
                    Return CType(Me(Me.tablebank.nameColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablebank.nameColumn) = value
            End Set
        End Property
        
        Public Property flag As Boolean
            Get
                Try 
                    Return CType(Me(Me.tablebank.flagColumn),Boolean)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablebank.flagColumn) = value
            End Set
        End Property
        
        Public Function IsnameNull() As Boolean
            Return Me.IsNull(Me.tablebank.nameColumn)
        End Function
        
        Public Sub SetnameNull()
            Me(Me.tablebank.nameColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsflagNull() As Boolean
            Return Me.IsNull(Me.tablebank.flagColumn)
        End Function
        
        Public Sub SetflagNull()
            Me(Me.tablebank.flagColumn) = System.Convert.DBNull
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class bankRowChangeEvent
        Inherits EventArgs
        
        Private eventRow As bankRow
        
        Private eventAction As DataRowAction
        
        Public Sub New(ByVal row As bankRow, ByVal action As DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        Public ReadOnly Property Row As bankRow
            Get
                Return Me.eventRow
            End Get
        End Property
        
        Public ReadOnly Property Action As DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class vendorDataTable
        Inherits DataTable
        Implements System.Collections.IEnumerable
        
        Private columncod As DataColumn
        
        Private columnname As DataColumn
        
        Private columnflag As DataColumn
        
        Friend Sub New()
            MyBase.New("vendor")
            Me.InitClass
        End Sub
        
        Friend Sub New(ByVal table As DataTable)
            MyBase.New(table.TableName)
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
            Me.DisplayExpression = table.DisplayExpression
        End Sub
        
        <System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        Friend ReadOnly Property codColumn As DataColumn
            Get
                Return Me.columncod
            End Get
        End Property
        
        Friend ReadOnly Property nameColumn As DataColumn
            Get
                Return Me.columnname
            End Get
        End Property
        
        Friend ReadOnly Property flagColumn As DataColumn
            Get
                Return Me.columnflag
            End Get
        End Property
        
        Public Default ReadOnly Property Item(ByVal index As Integer) As vendorRow
            Get
                Return CType(Me.Rows(index),vendorRow)
            End Get
        End Property
        
        Public Event vendorRowChanged As vendorRowChangeEventHandler
        
        Public Event vendorRowChanging As vendorRowChangeEventHandler
        
        Public Event vendorRowDeleted As vendorRowChangeEventHandler
        
        Public Event vendorRowDeleting As vendorRowChangeEventHandler
        
        Public Overloads Sub AddvendorRow(ByVal row As vendorRow)
            Me.Rows.Add(row)
        End Sub
        
        Public Overloads Function AddvendorRow(ByVal cod As String, ByVal name As String, ByVal flag As Boolean) As vendorRow
            Dim rowvendorRow As vendorRow = CType(Me.NewRow,vendorRow)
            rowvendorRow.ItemArray = New Object() {cod, name, flag}
            Me.Rows.Add(rowvendorRow)
            Return rowvendorRow
        End Function
        
        Public Function FindBycod(ByVal cod As String) As vendorRow
            Return CType(Me.Rows.Find(New Object() {cod}),vendorRow)
        End Function
        
        Public Function GetEnumerator() As System.Collections.IEnumerator Implements System.Collections.IEnumerable.GetEnumerator
            Return Me.Rows.GetEnumerator
        End Function
        
        Public Overrides Function Clone() As DataTable
            Dim cln As vendorDataTable = CType(MyBase.Clone,vendorDataTable)
            cln.InitVars
            Return cln
        End Function
        
        Protected Overrides Function CreateInstance() As DataTable
            Return New vendorDataTable
        End Function
        
        Friend Sub InitVars()
            Me.columncod = Me.Columns("cod")
            Me.columnname = Me.Columns("name")
            Me.columnflag = Me.Columns("flag")
        End Sub
        
        Private Sub InitClass()
            Me.columncod = New DataColumn("cod", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columncod)
            Me.columnname = New DataColumn("name", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnname)
            Me.columnflag = New DataColumn("flag", GetType(System.Boolean), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnflag)
            Me.Constraints.Add(New UniqueConstraint("Constraint1", New DataColumn() {Me.columncod}, true))
            Me.columncod.AllowDBNull = false
            Me.columncod.Unique = true
        End Sub
        
        Public Function NewvendorRow() As vendorRow
            Return CType(Me.NewRow,vendorRow)
        End Function
        
        Protected Overrides Function NewRowFromBuilder(ByVal builder As DataRowBuilder) As DataRow
            Return New vendorRow(builder)
        End Function
        
        Protected Overrides Function GetRowType() As System.Type
            Return GetType(vendorRow)
        End Function
        
        Protected Overrides Sub OnRowChanged(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.vendorRowChangedEvent) Is Nothing) Then
                RaiseEvent vendorRowChanged(Me, New vendorRowChangeEvent(CType(e.Row,vendorRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowChanging(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.vendorRowChangingEvent) Is Nothing) Then
                RaiseEvent vendorRowChanging(Me, New vendorRowChangeEvent(CType(e.Row,vendorRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleted(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.vendorRowDeletedEvent) Is Nothing) Then
                RaiseEvent vendorRowDeleted(Me, New vendorRowChangeEvent(CType(e.Row,vendorRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleting(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.vendorRowDeletingEvent) Is Nothing) Then
                RaiseEvent vendorRowDeleting(Me, New vendorRowChangeEvent(CType(e.Row,vendorRow), e.Action))
            End If
        End Sub
        
        Public Sub RemovevendorRow(ByVal row As vendorRow)
            Me.Rows.Remove(row)
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class vendorRow
        Inherits DataRow
        
        Private tablevendor As vendorDataTable
        
        Friend Sub New(ByVal rb As DataRowBuilder)
            MyBase.New(rb)
            Me.tablevendor = CType(Me.Table,vendorDataTable)
        End Sub
        
        Public Property cod As String
            Get
                Return CType(Me(Me.tablevendor.codColumn),String)
            End Get
            Set
                Me(Me.tablevendor.codColumn) = value
            End Set
        End Property
        
        Public Property name As String
            Get
                Try 
                    Return CType(Me(Me.tablevendor.nameColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablevendor.nameColumn) = value
            End Set
        End Property
        
        Public Property flag As Boolean
            Get
                Try 
                    Return CType(Me(Me.tablevendor.flagColumn),Boolean)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablevendor.flagColumn) = value
            End Set
        End Property
        
        Public Function IsnameNull() As Boolean
            Return Me.IsNull(Me.tablevendor.nameColumn)
        End Function
        
        Public Sub SetnameNull()
            Me(Me.tablevendor.nameColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsflagNull() As Boolean
            Return Me.IsNull(Me.tablevendor.flagColumn)
        End Function
        
        Public Sub SetflagNull()
            Me(Me.tablevendor.flagColumn) = System.Convert.DBNull
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class vendorRowChangeEvent
        Inherits EventArgs
        
        Private eventRow As vendorRow
        
        Private eventAction As DataRowAction
        
        Public Sub New(ByVal row As vendorRow, ByVal action As DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        Public ReadOnly Property Row As vendorRow
            Get
                Return Me.eventRow
            End Get
        End Property
        
        Public ReadOnly Property Action As DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class accountDataTable
        Inherits DataTable
        Implements System.Collections.IEnumerable
        
        Private columncod As DataColumn
        
        Private columnname As DataColumn
        
        Private columnflag As DataColumn
        
        Friend Sub New()
            MyBase.New("account")
            Me.InitClass
        End Sub
        
        Friend Sub New(ByVal table As DataTable)
            MyBase.New(table.TableName)
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
            Me.DisplayExpression = table.DisplayExpression
        End Sub
        
        <System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        Friend ReadOnly Property codColumn As DataColumn
            Get
                Return Me.columncod
            End Get
        End Property
        
        Friend ReadOnly Property nameColumn As DataColumn
            Get
                Return Me.columnname
            End Get
        End Property
        
        Friend ReadOnly Property flagColumn As DataColumn
            Get
                Return Me.columnflag
            End Get
        End Property
        
        Public Default ReadOnly Property Item(ByVal index As Integer) As accountRow
            Get
                Return CType(Me.Rows(index),accountRow)
            End Get
        End Property
        
        Public Event accountRowChanged As accountRowChangeEventHandler
        
        Public Event accountRowChanging As accountRowChangeEventHandler
        
        Public Event accountRowDeleted As accountRowChangeEventHandler
        
        Public Event accountRowDeleting As accountRowChangeEventHandler
        
        Public Overloads Sub AddaccountRow(ByVal row As accountRow)
            Me.Rows.Add(row)
        End Sub
        
        Public Overloads Function AddaccountRow(ByVal cod As String, ByVal name As String, ByVal flag As Boolean) As accountRow
            Dim rowaccountRow As accountRow = CType(Me.NewRow,accountRow)
            rowaccountRow.ItemArray = New Object() {cod, name, flag}
            Me.Rows.Add(rowaccountRow)
            Return rowaccountRow
        End Function
        
        Public Function FindBycod(ByVal cod As String) As accountRow
            Return CType(Me.Rows.Find(New Object() {cod}),accountRow)
        End Function
        
        Public Function GetEnumerator() As System.Collections.IEnumerator Implements System.Collections.IEnumerable.GetEnumerator
            Return Me.Rows.GetEnumerator
        End Function
        
        Public Overrides Function Clone() As DataTable
            Dim cln As accountDataTable = CType(MyBase.Clone,accountDataTable)
            cln.InitVars
            Return cln
        End Function
        
        Protected Overrides Function CreateInstance() As DataTable
            Return New accountDataTable
        End Function
        
        Friend Sub InitVars()
            Me.columncod = Me.Columns("cod")
            Me.columnname = Me.Columns("name")
            Me.columnflag = Me.Columns("flag")
        End Sub
        
        Private Sub InitClass()
            Me.columncod = New DataColumn("cod", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columncod)
            Me.columnname = New DataColumn("name", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnname)
            Me.columnflag = New DataColumn("flag", GetType(System.Boolean), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnflag)
            Me.Constraints.Add(New UniqueConstraint("Constraint1", New DataColumn() {Me.columncod}, true))
            Me.columncod.AllowDBNull = false
            Me.columncod.Unique = true
        End Sub
        
        Public Function NewaccountRow() As accountRow
            Return CType(Me.NewRow,accountRow)
        End Function
        
        Protected Overrides Function NewRowFromBuilder(ByVal builder As DataRowBuilder) As DataRow
            Return New accountRow(builder)
        End Function
        
        Protected Overrides Function GetRowType() As System.Type
            Return GetType(accountRow)
        End Function
        
        Protected Overrides Sub OnRowChanged(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.accountRowChangedEvent) Is Nothing) Then
                RaiseEvent accountRowChanged(Me, New accountRowChangeEvent(CType(e.Row,accountRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowChanging(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.accountRowChangingEvent) Is Nothing) Then
                RaiseEvent accountRowChanging(Me, New accountRowChangeEvent(CType(e.Row,accountRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleted(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.accountRowDeletedEvent) Is Nothing) Then
                RaiseEvent accountRowDeleted(Me, New accountRowChangeEvent(CType(e.Row,accountRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleting(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.accountRowDeletingEvent) Is Nothing) Then
                RaiseEvent accountRowDeleting(Me, New accountRowChangeEvent(CType(e.Row,accountRow), e.Action))
            End If
        End Sub
        
        Public Sub RemoveaccountRow(ByVal row As accountRow)
            Me.Rows.Remove(row)
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class accountRow
        Inherits DataRow
        
        Private tableaccount As accountDataTable
        
        Friend Sub New(ByVal rb As DataRowBuilder)
            MyBase.New(rb)
            Me.tableaccount = CType(Me.Table,accountDataTable)
        End Sub
        
        Public Property cod As String
            Get
                Return CType(Me(Me.tableaccount.codColumn),String)
            End Get
            Set
                Me(Me.tableaccount.codColumn) = value
            End Set
        End Property
        
        Public Property name As String
            Get
                Try 
                    Return CType(Me(Me.tableaccount.nameColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableaccount.nameColumn) = value
            End Set
        End Property
        
        Public Property flag As Boolean
            Get
                Try 
                    Return CType(Me(Me.tableaccount.flagColumn),Boolean)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableaccount.flagColumn) = value
            End Set
        End Property
        
        Public Function IsnameNull() As Boolean
            Return Me.IsNull(Me.tableaccount.nameColumn)
        End Function
        
        Public Sub SetnameNull()
            Me(Me.tableaccount.nameColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsflagNull() As Boolean
            Return Me.IsNull(Me.tableaccount.flagColumn)
        End Function
        
        Public Sub SetflagNull()
            Me(Me.tableaccount.flagColumn) = System.Convert.DBNull
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class accountRowChangeEvent
        Inherits EventArgs
        
        Private eventRow As accountRow
        
        Private eventAction As DataRowAction
        
        Public Sub New(ByVal row As accountRow, ByVal action As DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        Public ReadOnly Property Row As accountRow
            Get
                Return Me.eventRow
            End Get
        End Property
        
        Public ReadOnly Property Action As DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
End Class
