'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.573
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Data
Imports System.Runtime.Serialization
Imports System.Xml


<Serializable(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Diagnostics.DebuggerStepThrough(),  _
 System.ComponentModel.ToolboxItem(true)>  _
Public Class DSFrmEndOfDayInventoryAdjustment
    Inherits DataSet
    
    Private tableinv_adjustment_dtl As inv_adjustment_dtlDataTable
    
    Public Sub New()
        MyBase.New
        Me.InitClass
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    Protected Sub New(ByVal info As SerializationInfo, ByVal context As StreamingContext)
        MyBase.New
        Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(System.String)),String)
        If (Not (strSchema) Is Nothing) Then
            Dim ds As DataSet = New DataSet
            ds.ReadXmlSchema(New XmlTextReader(New System.IO.StringReader(strSchema)))
            If (Not (ds.Tables("inv_adjustment_dtl")) Is Nothing) Then
                Me.Tables.Add(New inv_adjustment_dtlDataTable(ds.Tables("inv_adjustment_dtl")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.InitClass
        End If
        Me.GetSerializationData(info, context)
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    <System.ComponentModel.Browsable(false),  _
     System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property inv_adjustment_dtl As inv_adjustment_dtlDataTable
        Get
            Return Me.tableinv_adjustment_dtl
        End Get
    End Property
    
    Public Overrides Function Clone() As DataSet
        Dim cln As DSFrmEndOfDayInventoryAdjustment = CType(MyBase.Clone,DSFrmEndOfDayInventoryAdjustment)
        cln.InitVars
        Return cln
    End Function
    
    Protected Overrides Function ShouldSerializeTables() As Boolean
        Return false
    End Function
    
    Protected Overrides Function ShouldSerializeRelations() As Boolean
        Return false
    End Function
    
    Protected Overrides Sub ReadXmlSerializable(ByVal reader As XmlReader)
        Me.Reset
        Dim ds As DataSet = New DataSet
        ds.ReadXml(reader)
        If (Not (ds.Tables("inv_adjustment_dtl")) Is Nothing) Then
            Me.Tables.Add(New inv_adjustment_dtlDataTable(ds.Tables("inv_adjustment_dtl")))
        End If
        Me.DataSetName = ds.DataSetName
        Me.Prefix = ds.Prefix
        Me.Namespace = ds.Namespace
        Me.Locale = ds.Locale
        Me.CaseSensitive = ds.CaseSensitive
        Me.EnforceConstraints = ds.EnforceConstraints
        Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
        Me.InitVars
    End Sub
    
    Protected Overrides Function GetSchemaSerializable() As System.Xml.Schema.XmlSchema
        Dim stream As System.IO.MemoryStream = New System.IO.MemoryStream
        Me.WriteXmlSchema(New XmlTextWriter(stream, Nothing))
        stream.Position = 0
        Return System.Xml.Schema.XmlSchema.Read(New XmlTextReader(stream), Nothing)
    End Function
    
    Friend Sub InitVars()
        Me.tableinv_adjustment_dtl = CType(Me.Tables("inv_adjustment_dtl"),inv_adjustment_dtlDataTable)
        If (Not (Me.tableinv_adjustment_dtl) Is Nothing) Then
            Me.tableinv_adjustment_dtl.InitVars
        End If
    End Sub
    
    Private Sub InitClass()
        Me.DataSetName = "DSFrmEndOfDayInventoryAdjustment"
        Me.Prefix = ""
        Me.Namespace = "http://www.tempuri.org/DSFrmEndOfDayInventoryAdjustment.xsd"
        Me.Locale = New System.Globalization.CultureInfo("fa-IR")
        Me.CaseSensitive = false
        Me.EnforceConstraints = true
        Me.tableinv_adjustment_dtl = New inv_adjustment_dtlDataTable
        Me.Tables.Add(Me.tableinv_adjustment_dtl)
    End Sub
    
    Private Function ShouldSerializeinv_adjustment_dtl() As Boolean
        Return false
    End Function
    
    Private Sub SchemaChanged(ByVal sender As Object, ByVal e As System.ComponentModel.CollectionChangeEventArgs)
        If (e.Action = System.ComponentModel.CollectionChangeAction.Remove) Then
            Me.InitVars
        End If
    End Sub
    
    Public Delegate Sub inv_adjustment_dtlRowChangeEventHandler(ByVal sender As Object, ByVal e As inv_adjustment_dtlRowChangeEvent)
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class inv_adjustment_dtlDataTable
        Inherits DataTable
        Implements System.Collections.IEnumerable
        
        Private columnreferID_adjustment As DataColumn
        
        Private columnitem_no As DataColumn
        
        Private columnQTY As DataColumn
        
        Private columndesc_item As DataColumn
        
        Private columnReplCost As DataColumn
        
        Private columnfet As DataColumn
        
        Private columnauthorized_by As DataColumn
        
        Private columnExtCost As DataColumn
        
        Friend Sub New()
            MyBase.New("inv_adjustment_dtl")
            Me.InitClass
        End Sub
        
        Friend Sub New(ByVal table As DataTable)
            MyBase.New(table.TableName)
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
            Me.DisplayExpression = table.DisplayExpression
        End Sub
        
        <System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        Friend ReadOnly Property referID_adjustmentColumn As DataColumn
            Get
                Return Me.columnreferID_adjustment
            End Get
        End Property
        
        Friend ReadOnly Property item_noColumn As DataColumn
            Get
                Return Me.columnitem_no
            End Get
        End Property
        
        Friend ReadOnly Property QTYColumn As DataColumn
            Get
                Return Me.columnQTY
            End Get
        End Property
        
        Friend ReadOnly Property desc_itemColumn As DataColumn
            Get
                Return Me.columndesc_item
            End Get
        End Property
        
        Friend ReadOnly Property ReplCostColumn As DataColumn
            Get
                Return Me.columnReplCost
            End Get
        End Property
        
        Friend ReadOnly Property fetColumn As DataColumn
            Get
                Return Me.columnfet
            End Get
        End Property
        
        Friend ReadOnly Property authorized_byColumn As DataColumn
            Get
                Return Me.columnauthorized_by
            End Get
        End Property
        
        Friend ReadOnly Property ExtCostColumn As DataColumn
            Get
                Return Me.columnExtCost
            End Get
        End Property
        
        Public Default ReadOnly Property Item(ByVal index As Integer) As inv_adjustment_dtlRow
            Get
                Return CType(Me.Rows(index),inv_adjustment_dtlRow)
            End Get
        End Property
        
        Public Event inv_adjustment_dtlRowChanged As inv_adjustment_dtlRowChangeEventHandler
        
        Public Event inv_adjustment_dtlRowChanging As inv_adjustment_dtlRowChangeEventHandler
        
        Public Event inv_adjustment_dtlRowDeleted As inv_adjustment_dtlRowChangeEventHandler
        
        Public Event inv_adjustment_dtlRowDeleting As inv_adjustment_dtlRowChangeEventHandler
        
        Public Overloads Sub Addinv_adjustment_dtlRow(ByVal row As inv_adjustment_dtlRow)
            Me.Rows.Add(row)
        End Sub
        
        Public Overloads Function Addinv_adjustment_dtlRow(ByVal referID_adjustment As String, ByVal item_no As String, ByVal QTY As Short, ByVal desc_item As String, ByVal ReplCost As Single, ByVal fet As Single, ByVal authorized_by As String, ByVal ExtCost As Decimal) As inv_adjustment_dtlRow
            Dim rowinv_adjustment_dtlRow As inv_adjustment_dtlRow = CType(Me.NewRow,inv_adjustment_dtlRow)
            rowinv_adjustment_dtlRow.ItemArray = New Object() {referID_adjustment, item_no, QTY, desc_item, ReplCost, fet, authorized_by, ExtCost}
            Me.Rows.Add(rowinv_adjustment_dtlRow)
            Return rowinv_adjustment_dtlRow
        End Function
        
        Public Function GetEnumerator() As System.Collections.IEnumerator Implements System.Collections.IEnumerable.GetEnumerator
            Return Me.Rows.GetEnumerator
        End Function
        
        Public Overrides Function Clone() As DataTable
            Dim cln As inv_adjustment_dtlDataTable = CType(MyBase.Clone,inv_adjustment_dtlDataTable)
            cln.InitVars
            Return cln
        End Function
        
        Protected Overrides Function CreateInstance() As DataTable
            Return New inv_adjustment_dtlDataTable
        End Function
        
        Friend Sub InitVars()
            Me.columnreferID_adjustment = Me.Columns("referID_adjustment")
            Me.columnitem_no = Me.Columns("item_no")
            Me.columnQTY = Me.Columns("QTY")
            Me.columndesc_item = Me.Columns("desc_item")
            Me.columnReplCost = Me.Columns("ReplCost")
            Me.columnfet = Me.Columns("fet")
            Me.columnauthorized_by = Me.Columns("authorized_by")
            Me.columnExtCost = Me.Columns("ExtCost")
        End Sub
        
        Private Sub InitClass()
            Me.columnreferID_adjustment = New DataColumn("referID_adjustment", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnreferID_adjustment)
            Me.columnitem_no = New DataColumn("item_no", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnitem_no)
            Me.columnQTY = New DataColumn("QTY", GetType(System.Int16), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnQTY)
            Me.columndesc_item = New DataColumn("desc_item", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columndesc_item)
            Me.columnReplCost = New DataColumn("ReplCost", GetType(System.Single), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnReplCost)
            Me.columnfet = New DataColumn("fet", GetType(System.Single), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnfet)
            Me.columnauthorized_by = New DataColumn("authorized_by", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnauthorized_by)
            Me.columnExtCost = New DataColumn("ExtCost", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnExtCost)
            Me.columnreferID_adjustment.AllowDBNull = false
            Me.columnitem_no.AllowDBNull = false
            Me.columnReplCost.ReadOnly = true
            Me.columnExtCost.ReadOnly = true
        End Sub
        
        Public Function Newinv_adjustment_dtlRow() As inv_adjustment_dtlRow
            Return CType(Me.NewRow,inv_adjustment_dtlRow)
        End Function
        
        Protected Overrides Function NewRowFromBuilder(ByVal builder As DataRowBuilder) As DataRow
            Return New inv_adjustment_dtlRow(builder)
        End Function
        
        Protected Overrides Function GetRowType() As System.Type
            Return GetType(inv_adjustment_dtlRow)
        End Function
        
        Protected Overrides Sub OnRowChanged(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.inv_adjustment_dtlRowChangedEvent) Is Nothing) Then
                RaiseEvent inv_adjustment_dtlRowChanged(Me, New inv_adjustment_dtlRowChangeEvent(CType(e.Row,inv_adjustment_dtlRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowChanging(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.inv_adjustment_dtlRowChangingEvent) Is Nothing) Then
                RaiseEvent inv_adjustment_dtlRowChanging(Me, New inv_adjustment_dtlRowChangeEvent(CType(e.Row,inv_adjustment_dtlRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleted(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.inv_adjustment_dtlRowDeletedEvent) Is Nothing) Then
                RaiseEvent inv_adjustment_dtlRowDeleted(Me, New inv_adjustment_dtlRowChangeEvent(CType(e.Row,inv_adjustment_dtlRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleting(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.inv_adjustment_dtlRowDeletingEvent) Is Nothing) Then
                RaiseEvent inv_adjustment_dtlRowDeleting(Me, New inv_adjustment_dtlRowChangeEvent(CType(e.Row,inv_adjustment_dtlRow), e.Action))
            End If
        End Sub
        
        Public Sub Removeinv_adjustment_dtlRow(ByVal row As inv_adjustment_dtlRow)
            Me.Rows.Remove(row)
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class inv_adjustment_dtlRow
        Inherits DataRow
        
        Private tableinv_adjustment_dtl As inv_adjustment_dtlDataTable
        
        Friend Sub New(ByVal rb As DataRowBuilder)
            MyBase.New(rb)
            Me.tableinv_adjustment_dtl = CType(Me.Table,inv_adjustment_dtlDataTable)
        End Sub
        
        Public Property referID_adjustment As String
            Get
                Return CType(Me(Me.tableinv_adjustment_dtl.referID_adjustmentColumn),String)
            End Get
            Set
                Me(Me.tableinv_adjustment_dtl.referID_adjustmentColumn) = value
            End Set
        End Property
        
        Public Property item_no As String
            Get
                Return CType(Me(Me.tableinv_adjustment_dtl.item_noColumn),String)
            End Get
            Set
                Me(Me.tableinv_adjustment_dtl.item_noColumn) = value
            End Set
        End Property
        
        Public Property QTY As Short
            Get
                Try 
                    Return CType(Me(Me.tableinv_adjustment_dtl.QTYColumn),Short)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableinv_adjustment_dtl.QTYColumn) = value
            End Set
        End Property
        
        Public Property desc_item As String
            Get
                Try 
                    Return CType(Me(Me.tableinv_adjustment_dtl.desc_itemColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableinv_adjustment_dtl.desc_itemColumn) = value
            End Set
        End Property
        
        Public Property ReplCost As Single
            Get
                Try 
                    Return CType(Me(Me.tableinv_adjustment_dtl.ReplCostColumn),Single)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableinv_adjustment_dtl.ReplCostColumn) = value
            End Set
        End Property
        
        Public Property fet As Single
            Get
                Try 
                    Return CType(Me(Me.tableinv_adjustment_dtl.fetColumn),Single)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableinv_adjustment_dtl.fetColumn) = value
            End Set
        End Property
        
        Public Property authorized_by As String
            Get
                Try 
                    Return CType(Me(Me.tableinv_adjustment_dtl.authorized_byColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableinv_adjustment_dtl.authorized_byColumn) = value
            End Set
        End Property
        
        Public Property ExtCost As Decimal
            Get
                Try 
                    Return CType(Me(Me.tableinv_adjustment_dtl.ExtCostColumn),Decimal)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableinv_adjustment_dtl.ExtCostColumn) = value
            End Set
        End Property
        
        Public Function IsQTYNull() As Boolean
            Return Me.IsNull(Me.tableinv_adjustment_dtl.QTYColumn)
        End Function
        
        Public Sub SetQTYNull()
            Me(Me.tableinv_adjustment_dtl.QTYColumn) = System.Convert.DBNull
        End Sub
        
        Public Function Isdesc_itemNull() As Boolean
            Return Me.IsNull(Me.tableinv_adjustment_dtl.desc_itemColumn)
        End Function
        
        Public Sub Setdesc_itemNull()
            Me(Me.tableinv_adjustment_dtl.desc_itemColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsReplCostNull() As Boolean
            Return Me.IsNull(Me.tableinv_adjustment_dtl.ReplCostColumn)
        End Function
        
        Public Sub SetReplCostNull()
            Me(Me.tableinv_adjustment_dtl.ReplCostColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsfetNull() As Boolean
            Return Me.IsNull(Me.tableinv_adjustment_dtl.fetColumn)
        End Function
        
        Public Sub SetfetNull()
            Me(Me.tableinv_adjustment_dtl.fetColumn) = System.Convert.DBNull
        End Sub
        
        Public Function Isauthorized_byNull() As Boolean
            Return Me.IsNull(Me.tableinv_adjustment_dtl.authorized_byColumn)
        End Function
        
        Public Sub Setauthorized_byNull()
            Me(Me.tableinv_adjustment_dtl.authorized_byColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsExtCostNull() As Boolean
            Return Me.IsNull(Me.tableinv_adjustment_dtl.ExtCostColumn)
        End Function
        
        Public Sub SetExtCostNull()
            Me(Me.tableinv_adjustment_dtl.ExtCostColumn) = System.Convert.DBNull
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class inv_adjustment_dtlRowChangeEvent
        Inherits EventArgs
        
        Private eventRow As inv_adjustment_dtlRow
        
        Private eventAction As DataRowAction
        
        Public Sub New(ByVal row As inv_adjustment_dtlRow, ByVal action As DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        Public ReadOnly Property Row As inv_adjustment_dtlRow
            Get
                Return Me.eventRow
            End Get
        End Property
        
        Public ReadOnly Property Action As DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
End Class
