'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.573
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Data
Imports System.Runtime.Serialization
Imports System.Xml


<Serializable(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Diagnostics.DebuggerStepThrough(),  _
 System.ComponentModel.ToolboxItem(true)>  _
Public Class DSFrmEndOfDayInventoryInterStoreSales
    Inherits DataSet
    
    Private tableinv_sales_transfer_dtl As inv_sales_transfer_dtlDataTable
    
    Public Sub New()
        MyBase.New
        Me.InitClass
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    Protected Sub New(ByVal info As SerializationInfo, ByVal context As StreamingContext)
        MyBase.New
        Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(System.String)),String)
        If (Not (strSchema) Is Nothing) Then
            Dim ds As DataSet = New DataSet
            ds.ReadXmlSchema(New XmlTextReader(New System.IO.StringReader(strSchema)))
            If (Not (ds.Tables("inv_sales_transfer_dtl")) Is Nothing) Then
                Me.Tables.Add(New inv_sales_transfer_dtlDataTable(ds.Tables("inv_sales_transfer_dtl")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.InitClass
        End If
        Me.GetSerializationData(info, context)
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    <System.ComponentModel.Browsable(false),  _
     System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property inv_sales_transfer_dtl As inv_sales_transfer_dtlDataTable
        Get
            Return Me.tableinv_sales_transfer_dtl
        End Get
    End Property
    
    Public Overrides Function Clone() As DataSet
        Dim cln As DSFrmEndOfDayInventoryInterStoreSales = CType(MyBase.Clone,DSFrmEndOfDayInventoryInterStoreSales)
        cln.InitVars
        Return cln
    End Function
    
    Protected Overrides Function ShouldSerializeTables() As Boolean
        Return false
    End Function
    
    Protected Overrides Function ShouldSerializeRelations() As Boolean
        Return false
    End Function
    
    Protected Overrides Sub ReadXmlSerializable(ByVal reader As XmlReader)
        Me.Reset
        Dim ds As DataSet = New DataSet
        ds.ReadXml(reader)
        If (Not (ds.Tables("inv_sales_transfer_dtl")) Is Nothing) Then
            Me.Tables.Add(New inv_sales_transfer_dtlDataTable(ds.Tables("inv_sales_transfer_dtl")))
        End If
        Me.DataSetName = ds.DataSetName
        Me.Prefix = ds.Prefix
        Me.Namespace = ds.Namespace
        Me.Locale = ds.Locale
        Me.CaseSensitive = ds.CaseSensitive
        Me.EnforceConstraints = ds.EnforceConstraints
        Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
        Me.InitVars
    End Sub
    
    Protected Overrides Function GetSchemaSerializable() As System.Xml.Schema.XmlSchema
        Dim stream As System.IO.MemoryStream = New System.IO.MemoryStream
        Me.WriteXmlSchema(New XmlTextWriter(stream, Nothing))
        stream.Position = 0
        Return System.Xml.Schema.XmlSchema.Read(New XmlTextReader(stream), Nothing)
    End Function
    
    Friend Sub InitVars()
        Me.tableinv_sales_transfer_dtl = CType(Me.Tables("inv_sales_transfer_dtl"),inv_sales_transfer_dtlDataTable)
        If (Not (Me.tableinv_sales_transfer_dtl) Is Nothing) Then
            Me.tableinv_sales_transfer_dtl.InitVars
        End If
    End Sub
    
    Private Sub InitClass()
        Me.DataSetName = "DSFrmEndOfDayInventoryInterStoreSales"
        Me.Prefix = ""
        Me.Namespace = "http://www.tempuri.org/DSFrmEndOfDayInventoryInterStoreSales.xsd"
        Me.Locale = New System.Globalization.CultureInfo("fa-IR")
        Me.CaseSensitive = false
        Me.EnforceConstraints = true
        Me.tableinv_sales_transfer_dtl = New inv_sales_transfer_dtlDataTable
        Me.Tables.Add(Me.tableinv_sales_transfer_dtl)
    End Sub
    
    Private Function ShouldSerializeinv_sales_transfer_dtl() As Boolean
        Return false
    End Function
    
    Private Sub SchemaChanged(ByVal sender As Object, ByVal e As System.ComponentModel.CollectionChangeEventArgs)
        If (e.Action = System.ComponentModel.CollectionChangeAction.Remove) Then
            Me.InitVars
        End If
    End Sub
    
    Public Delegate Sub inv_sales_transfer_dtlRowChangeEventHandler(ByVal sender As Object, ByVal e As inv_sales_transfer_dtlRowChangeEvent)
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class inv_sales_transfer_dtlDataTable
        Inherits DataTable
        Implements System.Collections.IEnumerable
        
        Private columnID_sales_transfer As DataColumn
        
        Private columnitem_no As DataColumn
        
        Private columnExtPrice As DataColumn
        
        Private columndesc_item As DataColumn
        
        Private columnReplCost As DataColumn
        
        Private columnstore_to As DataColumn
        
        Private columnqty As DataColumn
        
        Private columnExtCost As DataColumn
        
        Private columnfet As DataColumn
        
        Friend Sub New()
            MyBase.New("inv_sales_transfer_dtl")
            Me.InitClass
        End Sub
        
        Friend Sub New(ByVal table As DataTable)
            MyBase.New(table.TableName)
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
            Me.DisplayExpression = table.DisplayExpression
        End Sub
        
        <System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        Friend ReadOnly Property ID_sales_transferColumn As DataColumn
            Get
                Return Me.columnID_sales_transfer
            End Get
        End Property
        
        Friend ReadOnly Property item_noColumn As DataColumn
            Get
                Return Me.columnitem_no
            End Get
        End Property
        
        Friend ReadOnly Property ExtPriceColumn As DataColumn
            Get
                Return Me.columnExtPrice
            End Get
        End Property
        
        Friend ReadOnly Property desc_itemColumn As DataColumn
            Get
                Return Me.columndesc_item
            End Get
        End Property
        
        Friend ReadOnly Property ReplCostColumn As DataColumn
            Get
                Return Me.columnReplCost
            End Get
        End Property
        
        Friend ReadOnly Property store_toColumn As DataColumn
            Get
                Return Me.columnstore_to
            End Get
        End Property
        
        Friend ReadOnly Property qtyColumn As DataColumn
            Get
                Return Me.columnqty
            End Get
        End Property
        
        Friend ReadOnly Property ExtCostColumn As DataColumn
            Get
                Return Me.columnExtCost
            End Get
        End Property
        
        Friend ReadOnly Property fetColumn As DataColumn
            Get
                Return Me.columnfet
            End Get
        End Property
        
        Public Default ReadOnly Property Item(ByVal index As Integer) As inv_sales_transfer_dtlRow
            Get
                Return CType(Me.Rows(index),inv_sales_transfer_dtlRow)
            End Get
        End Property
        
        Public Event inv_sales_transfer_dtlRowChanged As inv_sales_transfer_dtlRowChangeEventHandler
        
        Public Event inv_sales_transfer_dtlRowChanging As inv_sales_transfer_dtlRowChangeEventHandler
        
        Public Event inv_sales_transfer_dtlRowDeleted As inv_sales_transfer_dtlRowChangeEventHandler
        
        Public Event inv_sales_transfer_dtlRowDeleting As inv_sales_transfer_dtlRowChangeEventHandler
        
        Public Overloads Sub Addinv_sales_transfer_dtlRow(ByVal row As inv_sales_transfer_dtlRow)
            Me.Rows.Add(row)
        End Sub
        
        Public Overloads Function Addinv_sales_transfer_dtlRow(ByVal ID_sales_transfer As String, ByVal item_no As String, ByVal ExtPrice As Decimal, ByVal desc_item As String, ByVal ReplCost As Single, ByVal store_to As String, ByVal qty As Decimal, ByVal ExtCost As Single, ByVal fet As Single) As inv_sales_transfer_dtlRow
            Dim rowinv_sales_transfer_dtlRow As inv_sales_transfer_dtlRow = CType(Me.NewRow,inv_sales_transfer_dtlRow)
            rowinv_sales_transfer_dtlRow.ItemArray = New Object() {ID_sales_transfer, item_no, ExtPrice, desc_item, ReplCost, store_to, qty, ExtCost, fet}
            Me.Rows.Add(rowinv_sales_transfer_dtlRow)
            Return rowinv_sales_transfer_dtlRow
        End Function
        
        Public Function GetEnumerator() As System.Collections.IEnumerator Implements System.Collections.IEnumerable.GetEnumerator
            Return Me.Rows.GetEnumerator
        End Function
        
        Public Overrides Function Clone() As DataTable
            Dim cln As inv_sales_transfer_dtlDataTable = CType(MyBase.Clone,inv_sales_transfer_dtlDataTable)
            cln.InitVars
            Return cln
        End Function
        
        Protected Overrides Function CreateInstance() As DataTable
            Return New inv_sales_transfer_dtlDataTable
        End Function
        
        Friend Sub InitVars()
            Me.columnID_sales_transfer = Me.Columns("ID_sales_transfer")
            Me.columnitem_no = Me.Columns("item_no")
            Me.columnExtPrice = Me.Columns("ExtPrice")
            Me.columndesc_item = Me.Columns("desc_item")
            Me.columnReplCost = Me.Columns("ReplCost")
            Me.columnstore_to = Me.Columns("store_to")
            Me.columnqty = Me.Columns("qty")
            Me.columnExtCost = Me.Columns("ExtCost")
            Me.columnfet = Me.Columns("fet")
        End Sub
        
        Private Sub InitClass()
            Me.columnID_sales_transfer = New DataColumn("ID_sales_transfer", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnID_sales_transfer)
            Me.columnitem_no = New DataColumn("item_no", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnitem_no)
            Me.columnExtPrice = New DataColumn("ExtPrice", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnExtPrice)
            Me.columndesc_item = New DataColumn("desc_item", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columndesc_item)
            Me.columnReplCost = New DataColumn("ReplCost", GetType(System.Single), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnReplCost)
            Me.columnstore_to = New DataColumn("store_to", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnstore_to)
            Me.columnqty = New DataColumn("qty", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnqty)
            Me.columnExtCost = New DataColumn("ExtCost", GetType(System.Single), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnExtCost)
            Me.columnfet = New DataColumn("fet", GetType(System.Single), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnfet)
            Me.columnID_sales_transfer.AllowDBNull = false
            Me.columnitem_no.AllowDBNull = false
            Me.columnExtPrice.ReadOnly = true
            Me.columnReplCost.ReadOnly = true
            Me.columnExtCost.ReadOnly = true
        End Sub
        
        Public Function Newinv_sales_transfer_dtlRow() As inv_sales_transfer_dtlRow
            Return CType(Me.NewRow,inv_sales_transfer_dtlRow)
        End Function
        
        Protected Overrides Function NewRowFromBuilder(ByVal builder As DataRowBuilder) As DataRow
            Return New inv_sales_transfer_dtlRow(builder)
        End Function
        
        Protected Overrides Function GetRowType() As System.Type
            Return GetType(inv_sales_transfer_dtlRow)
        End Function
        
        Protected Overrides Sub OnRowChanged(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.inv_sales_transfer_dtlRowChangedEvent) Is Nothing) Then
                RaiseEvent inv_sales_transfer_dtlRowChanged(Me, New inv_sales_transfer_dtlRowChangeEvent(CType(e.Row,inv_sales_transfer_dtlRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowChanging(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.inv_sales_transfer_dtlRowChangingEvent) Is Nothing) Then
                RaiseEvent inv_sales_transfer_dtlRowChanging(Me, New inv_sales_transfer_dtlRowChangeEvent(CType(e.Row,inv_sales_transfer_dtlRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleted(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.inv_sales_transfer_dtlRowDeletedEvent) Is Nothing) Then
                RaiseEvent inv_sales_transfer_dtlRowDeleted(Me, New inv_sales_transfer_dtlRowChangeEvent(CType(e.Row,inv_sales_transfer_dtlRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleting(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.inv_sales_transfer_dtlRowDeletingEvent) Is Nothing) Then
                RaiseEvent inv_sales_transfer_dtlRowDeleting(Me, New inv_sales_transfer_dtlRowChangeEvent(CType(e.Row,inv_sales_transfer_dtlRow), e.Action))
            End If
        End Sub
        
        Public Sub Removeinv_sales_transfer_dtlRow(ByVal row As inv_sales_transfer_dtlRow)
            Me.Rows.Remove(row)
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class inv_sales_transfer_dtlRow
        Inherits DataRow
        
        Private tableinv_sales_transfer_dtl As inv_sales_transfer_dtlDataTable
        
        Friend Sub New(ByVal rb As DataRowBuilder)
            MyBase.New(rb)
            Me.tableinv_sales_transfer_dtl = CType(Me.Table,inv_sales_transfer_dtlDataTable)
        End Sub
        
        Public Property ID_sales_transfer As String
            Get
                Return CType(Me(Me.tableinv_sales_transfer_dtl.ID_sales_transferColumn),String)
            End Get
            Set
                Me(Me.tableinv_sales_transfer_dtl.ID_sales_transferColumn) = value
            End Set
        End Property
        
        Public Property item_no As String
            Get
                Return CType(Me(Me.tableinv_sales_transfer_dtl.item_noColumn),String)
            End Get
            Set
                Me(Me.tableinv_sales_transfer_dtl.item_noColumn) = value
            End Set
        End Property
        
        Public Property ExtPrice As Decimal
            Get
                Try 
                    Return CType(Me(Me.tableinv_sales_transfer_dtl.ExtPriceColumn),Decimal)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableinv_sales_transfer_dtl.ExtPriceColumn) = value
            End Set
        End Property
        
        Public Property desc_item As String
            Get
                Try 
                    Return CType(Me(Me.tableinv_sales_transfer_dtl.desc_itemColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableinv_sales_transfer_dtl.desc_itemColumn) = value
            End Set
        End Property
        
        Public Property ReplCost As Single
            Get
                Try 
                    Return CType(Me(Me.tableinv_sales_transfer_dtl.ReplCostColumn),Single)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableinv_sales_transfer_dtl.ReplCostColumn) = value
            End Set
        End Property
        
        Public Property store_to As String
            Get
                Try 
                    Return CType(Me(Me.tableinv_sales_transfer_dtl.store_toColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableinv_sales_transfer_dtl.store_toColumn) = value
            End Set
        End Property
        
        Public Property qty As Decimal
            Get
                Try 
                    Return CType(Me(Me.tableinv_sales_transfer_dtl.qtyColumn),Decimal)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableinv_sales_transfer_dtl.qtyColumn) = value
            End Set
        End Property
        
        Public Property ExtCost As Single
            Get
                Try 
                    Return CType(Me(Me.tableinv_sales_transfer_dtl.ExtCostColumn),Single)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableinv_sales_transfer_dtl.ExtCostColumn) = value
            End Set
        End Property
        
        Public Property fet As Single
            Get
                Try 
                    Return CType(Me(Me.tableinv_sales_transfer_dtl.fetColumn),Single)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableinv_sales_transfer_dtl.fetColumn) = value
            End Set
        End Property
        
        Public Function IsExtPriceNull() As Boolean
            Return Me.IsNull(Me.tableinv_sales_transfer_dtl.ExtPriceColumn)
        End Function
        
        Public Sub SetExtPriceNull()
            Me(Me.tableinv_sales_transfer_dtl.ExtPriceColumn) = System.Convert.DBNull
        End Sub
        
        Public Function Isdesc_itemNull() As Boolean
            Return Me.IsNull(Me.tableinv_sales_transfer_dtl.desc_itemColumn)
        End Function
        
        Public Sub Setdesc_itemNull()
            Me(Me.tableinv_sales_transfer_dtl.desc_itemColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsReplCostNull() As Boolean
            Return Me.IsNull(Me.tableinv_sales_transfer_dtl.ReplCostColumn)
        End Function
        
        Public Sub SetReplCostNull()
            Me(Me.tableinv_sales_transfer_dtl.ReplCostColumn) = System.Convert.DBNull
        End Sub
        
        Public Function Isstore_toNull() As Boolean
            Return Me.IsNull(Me.tableinv_sales_transfer_dtl.store_toColumn)
        End Function
        
        Public Sub Setstore_toNull()
            Me(Me.tableinv_sales_transfer_dtl.store_toColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsqtyNull() As Boolean
            Return Me.IsNull(Me.tableinv_sales_transfer_dtl.qtyColumn)
        End Function
        
        Public Sub SetqtyNull()
            Me(Me.tableinv_sales_transfer_dtl.qtyColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsExtCostNull() As Boolean
            Return Me.IsNull(Me.tableinv_sales_transfer_dtl.ExtCostColumn)
        End Function
        
        Public Sub SetExtCostNull()
            Me(Me.tableinv_sales_transfer_dtl.ExtCostColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsfetNull() As Boolean
            Return Me.IsNull(Me.tableinv_sales_transfer_dtl.fetColumn)
        End Function
        
        Public Sub SetfetNull()
            Me(Me.tableinv_sales_transfer_dtl.fetColumn) = System.Convert.DBNull
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class inv_sales_transfer_dtlRowChangeEvent
        Inherits EventArgs
        
        Private eventRow As inv_sales_transfer_dtlRow
        
        Private eventAction As DataRowAction
        
        Public Sub New(ByVal row As inv_sales_transfer_dtlRow, ByVal action As DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        Public ReadOnly Property Row As inv_sales_transfer_dtlRow
            Get
                Return Me.eventRow
            End Get
        End Property
        
        Public ReadOnly Property Action As DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
End Class
