'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.573
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Data
Imports System.Runtime.Serialization
Imports System.Xml


<Serializable(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Diagnostics.DebuggerStepThrough(),  _
 System.ComponentModel.ToolboxItem(true)>  _
Public Class DSFrmSearchCheckScreen
    Inherits DataSet
    
    Private tablebank_check As bank_checkDataTable
    
    Public Sub New()
        MyBase.New
        Me.InitClass
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    Protected Sub New(ByVal info As SerializationInfo, ByVal context As StreamingContext)
        MyBase.New
        Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(System.String)),String)
        If (Not (strSchema) Is Nothing) Then
            Dim ds As DataSet = New DataSet
            ds.ReadXmlSchema(New XmlTextReader(New System.IO.StringReader(strSchema)))
            If (Not (ds.Tables("bank_check")) Is Nothing) Then
                Me.Tables.Add(New bank_checkDataTable(ds.Tables("bank_check")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.InitClass
        End If
        Me.GetSerializationData(info, context)
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    <System.ComponentModel.Browsable(false),  _
     System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property bank_check As bank_checkDataTable
        Get
            Return Me.tablebank_check
        End Get
    End Property
    
    Public Overrides Function Clone() As DataSet
        Dim cln As DSFrmSearchCheckScreen = CType(MyBase.Clone,DSFrmSearchCheckScreen)
        cln.InitVars
        Return cln
    End Function
    
    Protected Overrides Function ShouldSerializeTables() As Boolean
        Return false
    End Function
    
    Protected Overrides Function ShouldSerializeRelations() As Boolean
        Return false
    End Function
    
    Protected Overrides Sub ReadXmlSerializable(ByVal reader As XmlReader)
        Me.Reset
        Dim ds As DataSet = New DataSet
        ds.ReadXml(reader)
        If (Not (ds.Tables("bank_check")) Is Nothing) Then
            Me.Tables.Add(New bank_checkDataTable(ds.Tables("bank_check")))
        End If
        Me.DataSetName = ds.DataSetName
        Me.Prefix = ds.Prefix
        Me.Namespace = ds.Namespace
        Me.Locale = ds.Locale
        Me.CaseSensitive = ds.CaseSensitive
        Me.EnforceConstraints = ds.EnforceConstraints
        Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
        Me.InitVars
    End Sub
    
    Protected Overrides Function GetSchemaSerializable() As System.Xml.Schema.XmlSchema
        Dim stream As System.IO.MemoryStream = New System.IO.MemoryStream
        Me.WriteXmlSchema(New XmlTextWriter(stream, Nothing))
        stream.Position = 0
        Return System.Xml.Schema.XmlSchema.Read(New XmlTextReader(stream), Nothing)
    End Function
    
    Friend Sub InitVars()
        Me.tablebank_check = CType(Me.Tables("bank_check"),bank_checkDataTable)
        If (Not (Me.tablebank_check) Is Nothing) Then
            Me.tablebank_check.InitVars
        End If
    End Sub
    
    Private Sub InitClass()
        Me.DataSetName = "DSFrmSearchCheckScreen"
        Me.Prefix = ""
        Me.Namespace = "http://www.tempuri.org/DSFrmSearchCheckScreen.xsd"
        Me.Locale = New System.Globalization.CultureInfo("en-US")
        Me.CaseSensitive = false
        Me.EnforceConstraints = true
        Me.tablebank_check = New bank_checkDataTable
        Me.Tables.Add(Me.tablebank_check)
    End Sub
    
    Private Function ShouldSerializebank_check() As Boolean
        Return false
    End Function
    
    Private Sub SchemaChanged(ByVal sender As Object, ByVal e As System.ComponentModel.CollectionChangeEventArgs)
        If (e.Action = System.ComponentModel.CollectionChangeAction.Remove) Then
            Me.InitVars
        End If
    End Sub
    
    Public Delegate Sub bank_checkRowChangeEventHandler(ByVal sender As Object, ByVal e As bank_checkRowChangeEvent)
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class bank_checkDataTable
        Inherits DataTable
        Implements System.Collections.IEnumerable
        
        Private columnid_check As DataColumn
        
        Private columnid_bank As DataColumn
        
        Private columnno_of_check As DataColumn
        
        Private columndate_of_check As DataColumn
        
        Private columnamount_check As DataColumn
        
        Private columncod_vendor As DataColumn
        
        Private columnemployee_code As DataColumn
        
        Private columnaddress_payee As DataColumn
        
        Private columnmemo_check As DataColumn
        
        Private columninvoice_no As DataColumn
        
        Private columnmanual_check As DataColumn
        
        Private columnprint_later As DataColumn
        
        Private columncleared_bank As DataColumn
        
        Private columnid_debit_deposit_head As DataColumn
        
        Private columndesc_vendor As DataColumn
        
        Private columncheck_status As DataColumn
        
        Private columnEmplyeeName As DataColumn
        
        Private columnname_bank As DataColumn
        
        Friend Sub New()
            MyBase.New("bank_check")
            Me.InitClass
        End Sub
        
        Friend Sub New(ByVal table As DataTable)
            MyBase.New(table.TableName)
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
            Me.DisplayExpression = table.DisplayExpression
        End Sub
        
        <System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        Friend ReadOnly Property id_checkColumn As DataColumn
            Get
                Return Me.columnid_check
            End Get
        End Property
        
        Friend ReadOnly Property id_bankColumn As DataColumn
            Get
                Return Me.columnid_bank
            End Get
        End Property
        
        Friend ReadOnly Property no_of_checkColumn As DataColumn
            Get
                Return Me.columnno_of_check
            End Get
        End Property
        
        Friend ReadOnly Property date_of_checkColumn As DataColumn
            Get
                Return Me.columndate_of_check
            End Get
        End Property
        
        Friend ReadOnly Property amount_checkColumn As DataColumn
            Get
                Return Me.columnamount_check
            End Get
        End Property
        
        Friend ReadOnly Property cod_vendorColumn As DataColumn
            Get
                Return Me.columncod_vendor
            End Get
        End Property
        
        Friend ReadOnly Property employee_codeColumn As DataColumn
            Get
                Return Me.columnemployee_code
            End Get
        End Property
        
        Friend ReadOnly Property address_payeeColumn As DataColumn
            Get
                Return Me.columnaddress_payee
            End Get
        End Property
        
        Friend ReadOnly Property memo_checkColumn As DataColumn
            Get
                Return Me.columnmemo_check
            End Get
        End Property
        
        Friend ReadOnly Property invoice_noColumn As DataColumn
            Get
                Return Me.columninvoice_no
            End Get
        End Property
        
        Friend ReadOnly Property manual_checkColumn As DataColumn
            Get
                Return Me.columnmanual_check
            End Get
        End Property
        
        Friend ReadOnly Property print_laterColumn As DataColumn
            Get
                Return Me.columnprint_later
            End Get
        End Property
        
        Friend ReadOnly Property cleared_bankColumn As DataColumn
            Get
                Return Me.columncleared_bank
            End Get
        End Property
        
        Friend ReadOnly Property id_debit_deposit_headColumn As DataColumn
            Get
                Return Me.columnid_debit_deposit_head
            End Get
        End Property
        
        Friend ReadOnly Property desc_vendorColumn As DataColumn
            Get
                Return Me.columndesc_vendor
            End Get
        End Property
        
        Friend ReadOnly Property check_statusColumn As DataColumn
            Get
                Return Me.columncheck_status
            End Get
        End Property
        
        Friend ReadOnly Property EmplyeeNameColumn As DataColumn
            Get
                Return Me.columnEmplyeeName
            End Get
        End Property
        
        Friend ReadOnly Property name_bankColumn As DataColumn
            Get
                Return Me.columnname_bank
            End Get
        End Property
        
        Public Default ReadOnly Property Item(ByVal index As Integer) As bank_checkRow
            Get
                Return CType(Me.Rows(index),bank_checkRow)
            End Get
        End Property
        
        Public Event bank_checkRowChanged As bank_checkRowChangeEventHandler
        
        Public Event bank_checkRowChanging As bank_checkRowChangeEventHandler
        
        Public Event bank_checkRowDeleted As bank_checkRowChangeEventHandler
        
        Public Event bank_checkRowDeleting As bank_checkRowChangeEventHandler
        
        Public Overloads Sub Addbank_checkRow(ByVal row As bank_checkRow)
            Me.Rows.Add(row)
        End Sub
        
        Public Overloads Function Addbank_checkRow( _
                    ByVal id_bank As Short,  _
                    ByVal no_of_check As String,  _
                    ByVal date_of_check As String,  _
                    ByVal amount_check As Decimal,  _
                    ByVal cod_vendor As String,  _
                    ByVal employee_code As String,  _
                    ByVal address_payee As String,  _
                    ByVal memo_check As String,  _
                    ByVal invoice_no As String,  _
                    ByVal manual_check As Boolean,  _
                    ByVal print_later As Boolean,  _
                    ByVal cleared_bank As Boolean,  _
                    ByVal id_debit_deposit_head As Integer,  _
                    ByVal desc_vendor As String,  _
                    ByVal check_status As String,  _
                    ByVal EmplyeeName As String,  _
                    ByVal name_bank As String) As bank_checkRow
            Dim rowbank_checkRow As bank_checkRow = CType(Me.NewRow,bank_checkRow)
            rowbank_checkRow.ItemArray = New Object() {Nothing, id_bank, no_of_check, date_of_check, amount_check, cod_vendor, employee_code, address_payee, memo_check, invoice_no, manual_check, print_later, cleared_bank, id_debit_deposit_head, desc_vendor, check_status, EmplyeeName, name_bank}
            Me.Rows.Add(rowbank_checkRow)
            Return rowbank_checkRow
        End Function
        
        Public Function GetEnumerator() As System.Collections.IEnumerator Implements System.Collections.IEnumerable.GetEnumerator
            Return Me.Rows.GetEnumerator
        End Function
        
        Public Overrides Function Clone() As DataTable
            Dim cln As bank_checkDataTable = CType(MyBase.Clone,bank_checkDataTable)
            cln.InitVars
            Return cln
        End Function
        
        Protected Overrides Function CreateInstance() As DataTable
            Return New bank_checkDataTable
        End Function
        
        Friend Sub InitVars()
            Me.columnid_check = Me.Columns("id_check")
            Me.columnid_bank = Me.Columns("id_bank")
            Me.columnno_of_check = Me.Columns("no_of_check")
            Me.columndate_of_check = Me.Columns("date_of_check")
            Me.columnamount_check = Me.Columns("amount_check")
            Me.columncod_vendor = Me.Columns("cod_vendor")
            Me.columnemployee_code = Me.Columns("employee_code")
            Me.columnaddress_payee = Me.Columns("address_payee")
            Me.columnmemo_check = Me.Columns("memo_check")
            Me.columninvoice_no = Me.Columns("invoice_no")
            Me.columnmanual_check = Me.Columns("manual_check")
            Me.columnprint_later = Me.Columns("print_later")
            Me.columncleared_bank = Me.Columns("cleared_bank")
            Me.columnid_debit_deposit_head = Me.Columns("id_debit_deposit_head")
            Me.columndesc_vendor = Me.Columns("desc_vendor")
            Me.columncheck_status = Me.Columns("check_status")
            Me.columnEmplyeeName = Me.Columns("EmplyeeName")
            Me.columnname_bank = Me.Columns("name_bank")
        End Sub
        
        Private Sub InitClass()
            Me.columnid_check = New DataColumn("id_check", GetType(System.Int32), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnid_check)
            Me.columnid_bank = New DataColumn("id_bank", GetType(System.Int16), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnid_bank)
            Me.columnno_of_check = New DataColumn("no_of_check", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnno_of_check)
            Me.columndate_of_check = New DataColumn("date_of_check", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columndate_of_check)
            Me.columnamount_check = New DataColumn("amount_check", GetType(System.Decimal), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnamount_check)
            Me.columncod_vendor = New DataColumn("cod_vendor", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columncod_vendor)
            Me.columnemployee_code = New DataColumn("employee_code", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnemployee_code)
            Me.columnaddress_payee = New DataColumn("address_payee", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnaddress_payee)
            Me.columnmemo_check = New DataColumn("memo_check", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnmemo_check)
            Me.columninvoice_no = New DataColumn("invoice_no", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columninvoice_no)
            Me.columnmanual_check = New DataColumn("manual_check", GetType(System.Boolean), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnmanual_check)
            Me.columnprint_later = New DataColumn("print_later", GetType(System.Boolean), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnprint_later)
            Me.columncleared_bank = New DataColumn("cleared_bank", GetType(System.Boolean), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columncleared_bank)
            Me.columnid_debit_deposit_head = New DataColumn("id_debit_deposit_head", GetType(System.Int32), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnid_debit_deposit_head)
            Me.columndesc_vendor = New DataColumn("desc_vendor", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columndesc_vendor)
            Me.columncheck_status = New DataColumn("check_status", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columncheck_status)
            Me.columnEmplyeeName = New DataColumn("EmplyeeName", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnEmplyeeName)
            Me.columnname_bank = New DataColumn("name_bank", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnname_bank)
            Me.columnid_check.AutoIncrement = true
            Me.columnid_check.AllowDBNull = false
            Me.columnid_check.ReadOnly = true
            Me.columncheck_status.ReadOnly = true
            Me.columnEmplyeeName.ReadOnly = true
        End Sub
        
        Public Function Newbank_checkRow() As bank_checkRow
            Return CType(Me.NewRow,bank_checkRow)
        End Function
        
        Protected Overrides Function NewRowFromBuilder(ByVal builder As DataRowBuilder) As DataRow
            Return New bank_checkRow(builder)
        End Function
        
        Protected Overrides Function GetRowType() As System.Type
            Return GetType(bank_checkRow)
        End Function
        
        Protected Overrides Sub OnRowChanged(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.bank_checkRowChangedEvent) Is Nothing) Then
                RaiseEvent bank_checkRowChanged(Me, New bank_checkRowChangeEvent(CType(e.Row,bank_checkRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowChanging(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.bank_checkRowChangingEvent) Is Nothing) Then
                RaiseEvent bank_checkRowChanging(Me, New bank_checkRowChangeEvent(CType(e.Row,bank_checkRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleted(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.bank_checkRowDeletedEvent) Is Nothing) Then
                RaiseEvent bank_checkRowDeleted(Me, New bank_checkRowChangeEvent(CType(e.Row,bank_checkRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleting(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.bank_checkRowDeletingEvent) Is Nothing) Then
                RaiseEvent bank_checkRowDeleting(Me, New bank_checkRowChangeEvent(CType(e.Row,bank_checkRow), e.Action))
            End If
        End Sub
        
        Public Sub Removebank_checkRow(ByVal row As bank_checkRow)
            Me.Rows.Remove(row)
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class bank_checkRow
        Inherits DataRow
        
        Private tablebank_check As bank_checkDataTable
        
        Friend Sub New(ByVal rb As DataRowBuilder)
            MyBase.New(rb)
            Me.tablebank_check = CType(Me.Table,bank_checkDataTable)
        End Sub
        
        Public Property id_check As Integer
            Get
                Return CType(Me(Me.tablebank_check.id_checkColumn),Integer)
            End Get
            Set
                Me(Me.tablebank_check.id_checkColumn) = value
            End Set
        End Property
        
        Public Property id_bank As Short
            Get
                Try 
                    Return CType(Me(Me.tablebank_check.id_bankColumn),Short)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablebank_check.id_bankColumn) = value
            End Set
        End Property
        
        Public Property no_of_check As String
            Get
                Try 
                    Return CType(Me(Me.tablebank_check.no_of_checkColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablebank_check.no_of_checkColumn) = value
            End Set
        End Property
        
        Public Property date_of_check As String
            Get
                Try 
                    Return CType(Me(Me.tablebank_check.date_of_checkColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablebank_check.date_of_checkColumn) = value
            End Set
        End Property
        
        Public Property amount_check As Decimal
            Get
                Try 
                    Return CType(Me(Me.tablebank_check.amount_checkColumn),Decimal)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablebank_check.amount_checkColumn) = value
            End Set
        End Property
        
        Public Property cod_vendor As String
            Get
                Try 
                    Return CType(Me(Me.tablebank_check.cod_vendorColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablebank_check.cod_vendorColumn) = value
            End Set
        End Property
        
        Public Property employee_code As String
            Get
                Try 
                    Return CType(Me(Me.tablebank_check.employee_codeColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablebank_check.employee_codeColumn) = value
            End Set
        End Property
        
        Public Property address_payee As String
            Get
                Try 
                    Return CType(Me(Me.tablebank_check.address_payeeColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablebank_check.address_payeeColumn) = value
            End Set
        End Property
        
        Public Property memo_check As String
            Get
                Try 
                    Return CType(Me(Me.tablebank_check.memo_checkColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablebank_check.memo_checkColumn) = value
            End Set
        End Property
        
        Public Property invoice_no As String
            Get
                Try 
                    Return CType(Me(Me.tablebank_check.invoice_noColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablebank_check.invoice_noColumn) = value
            End Set
        End Property
        
        Public Property manual_check As Boolean
            Get
                Try 
                    Return CType(Me(Me.tablebank_check.manual_checkColumn),Boolean)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablebank_check.manual_checkColumn) = value
            End Set
        End Property
        
        Public Property print_later As Boolean
            Get
                Try 
                    Return CType(Me(Me.tablebank_check.print_laterColumn),Boolean)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablebank_check.print_laterColumn) = value
            End Set
        End Property
        
        Public Property cleared_bank As Boolean
            Get
                Try 
                    Return CType(Me(Me.tablebank_check.cleared_bankColumn),Boolean)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablebank_check.cleared_bankColumn) = value
            End Set
        End Property
        
        Public Property id_debit_deposit_head As Integer
            Get
                Try 
                    Return CType(Me(Me.tablebank_check.id_debit_deposit_headColumn),Integer)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablebank_check.id_debit_deposit_headColumn) = value
            End Set
        End Property
        
        Public Property desc_vendor As String
            Get
                Try 
                    Return CType(Me(Me.tablebank_check.desc_vendorColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablebank_check.desc_vendorColumn) = value
            End Set
        End Property
        
        Public Property check_status As String
            Get
                Try 
                    Return CType(Me(Me.tablebank_check.check_statusColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablebank_check.check_statusColumn) = value
            End Set
        End Property
        
        Public Property EmplyeeName As String
            Get
                Try 
                    Return CType(Me(Me.tablebank_check.EmplyeeNameColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablebank_check.EmplyeeNameColumn) = value
            End Set
        End Property
        
        Public Property name_bank As String
            Get
                Try 
                    Return CType(Me(Me.tablebank_check.name_bankColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablebank_check.name_bankColumn) = value
            End Set
        End Property
        
        Public Function Isid_bankNull() As Boolean
            Return Me.IsNull(Me.tablebank_check.id_bankColumn)
        End Function
        
        Public Sub Setid_bankNull()
            Me(Me.tablebank_check.id_bankColumn) = System.Convert.DBNull
        End Sub
        
        Public Function Isno_of_checkNull() As Boolean
            Return Me.IsNull(Me.tablebank_check.no_of_checkColumn)
        End Function
        
        Public Sub Setno_of_checkNull()
            Me(Me.tablebank_check.no_of_checkColumn) = System.Convert.DBNull
        End Sub
        
        Public Function Isdate_of_checkNull() As Boolean
            Return Me.IsNull(Me.tablebank_check.date_of_checkColumn)
        End Function
        
        Public Sub Setdate_of_checkNull()
            Me(Me.tablebank_check.date_of_checkColumn) = System.Convert.DBNull
        End Sub
        
        Public Function Isamount_checkNull() As Boolean
            Return Me.IsNull(Me.tablebank_check.amount_checkColumn)
        End Function
        
        Public Sub Setamount_checkNull()
            Me(Me.tablebank_check.amount_checkColumn) = System.Convert.DBNull
        End Sub
        
        Public Function Iscod_vendorNull() As Boolean
            Return Me.IsNull(Me.tablebank_check.cod_vendorColumn)
        End Function
        
        Public Sub Setcod_vendorNull()
            Me(Me.tablebank_check.cod_vendorColumn) = System.Convert.DBNull
        End Sub
        
        Public Function Isemployee_codeNull() As Boolean
            Return Me.IsNull(Me.tablebank_check.employee_codeColumn)
        End Function
        
        Public Sub Setemployee_codeNull()
            Me(Me.tablebank_check.employee_codeColumn) = System.Convert.DBNull
        End Sub
        
        Public Function Isaddress_payeeNull() As Boolean
            Return Me.IsNull(Me.tablebank_check.address_payeeColumn)
        End Function
        
        Public Sub Setaddress_payeeNull()
            Me(Me.tablebank_check.address_payeeColumn) = System.Convert.DBNull
        End Sub
        
        Public Function Ismemo_checkNull() As Boolean
            Return Me.IsNull(Me.tablebank_check.memo_checkColumn)
        End Function
        
        Public Sub Setmemo_checkNull()
            Me(Me.tablebank_check.memo_checkColumn) = System.Convert.DBNull
        End Sub
        
        Public Function Isinvoice_noNull() As Boolean
            Return Me.IsNull(Me.tablebank_check.invoice_noColumn)
        End Function
        
        Public Sub Setinvoice_noNull()
            Me(Me.tablebank_check.invoice_noColumn) = System.Convert.DBNull
        End Sub
        
        Public Function Ismanual_checkNull() As Boolean
            Return Me.IsNull(Me.tablebank_check.manual_checkColumn)
        End Function
        
        Public Sub Setmanual_checkNull()
            Me(Me.tablebank_check.manual_checkColumn) = System.Convert.DBNull
        End Sub
        
        Public Function Isprint_laterNull() As Boolean
            Return Me.IsNull(Me.tablebank_check.print_laterColumn)
        End Function
        
        Public Sub Setprint_laterNull()
            Me(Me.tablebank_check.print_laterColumn) = System.Convert.DBNull
        End Sub
        
        Public Function Iscleared_bankNull() As Boolean
            Return Me.IsNull(Me.tablebank_check.cleared_bankColumn)
        End Function
        
        Public Sub Setcleared_bankNull()
            Me(Me.tablebank_check.cleared_bankColumn) = System.Convert.DBNull
        End Sub
        
        Public Function Isid_debit_deposit_headNull() As Boolean
            Return Me.IsNull(Me.tablebank_check.id_debit_deposit_headColumn)
        End Function
        
        Public Sub Setid_debit_deposit_headNull()
            Me(Me.tablebank_check.id_debit_deposit_headColumn) = System.Convert.DBNull
        End Sub
        
        Public Function Isdesc_vendorNull() As Boolean
            Return Me.IsNull(Me.tablebank_check.desc_vendorColumn)
        End Function
        
        Public Sub Setdesc_vendorNull()
            Me(Me.tablebank_check.desc_vendorColumn) = System.Convert.DBNull
        End Sub
        
        Public Function Ischeck_statusNull() As Boolean
            Return Me.IsNull(Me.tablebank_check.check_statusColumn)
        End Function
        
        Public Sub Setcheck_statusNull()
            Me(Me.tablebank_check.check_statusColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsEmplyeeNameNull() As Boolean
            Return Me.IsNull(Me.tablebank_check.EmplyeeNameColumn)
        End Function
        
        Public Sub SetEmplyeeNameNull()
            Me(Me.tablebank_check.EmplyeeNameColumn) = System.Convert.DBNull
        End Sub
        
        Public Function Isname_bankNull() As Boolean
            Return Me.IsNull(Me.tablebank_check.name_bankColumn)
        End Function
        
        Public Sub Setname_bankNull()
            Me(Me.tablebank_check.name_bankColumn) = System.Convert.DBNull
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class bank_checkRowChangeEvent
        Inherits EventArgs
        
        Private eventRow As bank_checkRow
        
        Private eventAction As DataRowAction
        
        Public Sub New(ByVal row As bank_checkRow, ByVal action As DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        Public ReadOnly Property Row As bank_checkRow
            Get
                Return Me.eventRow
            End Get
        End Property
        
        Public ReadOnly Property Action As DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
End Class
